name: Push Pipline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install dependencies
        run: npm install

      # Add platform-tools to PATH
      - name: Add platform-tools to PATH
        run: echo "export PATH=\$PATH:/home/ics-30/Android/Sdk/platform-tools" >> $GITHUB_PATH

      - name: Run Prettier check
        run: npm run pretty

      - name: Run lint check
        run: npm run lint

      - name: Run test check
        run: npm run test
